package security

import (
	"strings"
	"testing"

	"golang.org/x/crypto/bcrypt"
)

func TestPBKDF2(t *testing.T) {
	password := "mySecurePassword123"
	
	// 1. Test hashing
	hash, err := HashPassword(password)
	if err != nil {
		t.Fatalf("Failed to hash password: %v", err)
	}
	
	t.Logf("Generated PBKDF2 hash: %s", hash)
	
	// Verify it starts with correct prefix
	if !strings.HasPrefix(hash, "pbkdf2_sha256$100000$") {
		t.Errorf("Hash does not have expected prefix, got: %s", hash)
	}
	
	// 2. Test correct password verification
	valid, err := VerifyPassword(hash, password)
	if err != nil {
		t.Fatalf("Error during verification: %v", err)
	}
	if !valid {
		t.Error("Expected correct password to verify successfully")
	}
	
	// 3. Test incorrect password verification
	valid, err = VerifyPassword(hash, "wrongPassword")
	if err != nil {
		t.Fatalf("Error during verification: %v", err)
	}
	if valid {
		t.Error("Expected incorrect password to fail verification")
	}
	
	// 4. Test legacy bcrypt verification
	bcryptHashBytes, err := bcrypt.GenerateFromPassword([]byte(password), 10)
	if err != nil {
		t.Fatalf("Failed to generate legacy bcrypt hash: %v", err)
	}
	bcryptHash := string(bcryptHashBytes)
	
	valid, err = VerifyPassword(bcryptHash, password)
	if err != nil {
		t.Fatalf("Error during legacy bcrypt verification: %v", err)
	}
	if !valid {
		t.Error("Expected legacy bcrypt hash to verify successfully")
	}
	
	valid, err = VerifyPassword(bcryptHash, "wrongPassword")
	if err != nil {
		t.Fatalf("Error during legacy bcrypt verification: %v", err)
	}
	if valid {
		t.Error("Expected incorrect password on legacy bcrypt hash to fail verification")
	}

	// 5. Cross-Compatibility: Test verifying a hash generated by the Node.js backend
	nodeHash := "pbkdf2_sha256$100000$d5d2108b47716bf653962b8b5b097e2a$3a7efddca7d2072ed5de11ec62db33696f516972ca54b20a4b3a7597d9577f7b"
	valid, err = VerifyPassword(nodeHash, password)
	if err != nil {
		t.Fatalf("Error verifying Node-generated hash in Go: %v", err)
	}
	if !valid {
		t.Error("Failed to verify Node-generated hash in Go (cross-compatibility failure)")
	}
}
